<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon />
    <StartupObject></StartupObject>
    <OutputPath>bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <PublishSingleFile Condition="'$(Configuration)'=='Release'">true</PublishSingleFile>
    <SelfContained Condition="'$(Configuration)'=='Release'">false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../M30Demo.Core/M30Demo.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(SolutionDir)yccard.dll" Condition="Exists('$(SolutionDir)yccard.dll')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
