//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SeaoryDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SEAORYDEMO_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DLG_COMMAND                 131
#define IDD_DLG_PRINT                   132
#define IDD_DLG_PRINT2                  133
#define IDD_DLG_MAGNETIC                134
#define IDD_DLG_SCARD                   135
#define IDD_DLG_UHF                     136
#define IDD_DLG_FM1208                  137
#define IDD_DLG_CONFIG                  138
#define IDD_DLG_RETRANSFER              140
#define IDD_DLG_CONCAVE                 142
#define IDD_DLG_CARD_INOUT              144
#define IDD_DLG_SECURITY                145
#define IDR_MENU1                       250
#define IDC_LANG_SYSTEM                 251
#define IDC_LANG_ENG                    252
#define IDC_LANG_CHS                    253
#define IDS_TAB_COMMAND                 301
#define IDS_TAB_CARD_INOUT              302
#define IDS_TAB_CONFIG                  303
#define IDS_TAB_RETRANSFER              304
#define IDS_TAB_PRINT                   305
#define IDS_TAB_PRINT2                  306
#define IDS_TAB_MAGNETIC                307
#define IDS_TAB_SMART_CARD              308
#define IDS_TAB_UHF                     309
#define IDS_TAB_FM1208                  310
#define IDS_TAB_CONCAVE                 311
#define IDS_TAB_SECURITY                312
#define IDS_ERROR                       501
#define IDS_SUCCESS                     502
#define IDS_READY                       503
#define IDS_PRINTER_NOT_CONNECTED       504
#define IDS_PRINTER_BUSY                505
#define IDS_STATUS                      506
#define IDS_INIT_COM_ERROR              507
#define IDS_LOAD_DLL_FAIL               508
#define IDS_INIT_COM_OK                 509
#define IDS_SELECT_TRACK                510
#define IDS_SELECT_TRACK_WRITE          511
#define IDS_INPUT_TRACK_1               512
#define IDS_INPUT_TRACK_2               513
#define IDS_INPUT_TRACK_3               514
#define IDS_MOVE_CARD_POS_1             515
#define IDS_MOVE_CARD_POS_2             516
#define IDS_MOVE_CARD_POS_3             517
#define IDS_MOVE_CARD_POS_4             518
#define IDS_MOVE_CARD_POS_5             519
#define IDS_MOVE_CARD_POS_6             520
#define IDS_MOVE_CARD_POS_7             521
#define IDS_MOVE_CARD_POS_8             522
#define IDS_MOVE_CARD_POS_9             523
#define IDS_MOVE_CARD_POS_10            524
#define IDS_MOVE_CARD_POS_11            525
#define IDS_MOVE_CARD_POS_12            526
#define IDS_MOVE_CARD_POS_13            527
#define IDS_MOVE_CARD_POS_14            528
#define IDS_PORTRAIT                    529
#define IDS_LANDSCAPE                   530
#define IDS_DITHER                      531
#define IDS_BLACK_WHITE                 532
#define IDS_K_OF_YMCKO1                 533
#define IDS_K_OF_YMCKO2                 534
#define IDS_K_OF_YMCKO3                 535
#define IDS_INFO_1                      536
#define IDS_INFO_2                      537
#define IDS_INFO_3                      538
#define IDS_INFO_4                      539
#define IDS_INFO_5                      540
#define IDS_INFO_6                      541
#define IDS_INFO_7                      542
#define IDS_INFO_8                      543
#define IDS_INFO_9                      544
#define IDS_INFO_10                     545
#define IDS_INFO_11                     546
#define IDS_INFO_12                     547
#define IDS_INFO_13                     548
#define IDS_INFO_14                     549
#define IDS_INFO_15                     550
#define IDS_INFO_16                     551
#define IDS_INFO_17                     552
#define IDS_INFO_18                     553
#define IDS_INFO_19                     554
#define IDS_INFO_20                     555
#define IDS_INFO_21                     556
#define IDS_INFO_22                     557
#define IDS_INFO_23                     558
#define IDS_INFO_24                     559
#define IDS_COMMAND_1                   560
#define IDS_COMMAND_2                   561
#define IDS_COMMAND_3                   562
#define IDS_COMMAND_4                   563
#define IDS_COMMAND_5                   564
#define IDS_COMMAND_6                   565
#define IDS_COMMAND_7                   566
#define IDS_COMMAND_8                   567
#define IDS_COMMAND_9                   568
#define IDS_LOCO                        569
#define IDS_HICO                        570
#define IDS_DATA_WRONG1                 571
#define IDS_DATA_WRONG2                 572
#define IDS_DATA_WRONG3                 573
#define IDS_FEED_CARD1                  574
#define IDS_FEED_CARD2                  575
#define IDS_FEED_CARD3                  576
#define IDS_FEED_CARD4                  577
#define IDS_EJECT_CARD1                 578
#define IDS_EJECT_CARD2                 579
#define IDS_EJECT_CARD3                 580
#define IDS_EJECT_CARD4                 581
#define IDS_EJECT_CARD5                 582
#define IDS_EJECT_CARD6                 583
#define IDS_TAKE_OFF_RIBBON             584
#define IDS_STANDBY_SIDE1               585
#define IDS_STANDBY_SIDE2               586
#define IDS_CARD_IN_SIGNAL1             587
#define IDS_CARD_IN_SIGNAL2             588
#define IDS_INIT_RIBBON_MODE1           589
#define IDS_INIT_RIBBON_MODE2           590
#define IDS_UHF_SECTION1                591
#define IDS_UHF_SECTION2                592
#define IDS_UHF_SECTION3                593
#define IDS_UHF_SECTION4                594
#define IDS_RETRANSFER_CARD_TYPE1       595
#define IDS_RETRANSFER_CARD_TYPE2       596
#define IDS_RETRANSFER_CARD_TYPE3       597
#define IDS_RETRANSFER_CARD_TYPE4       598
#define IDS_FLAT_MODE_OPT1              599
#define IDS_FLAT_MODE_OPT2              600
#define IDS_FLAT_MODE_OPT3              601
#define IDS_FLAT_MODE_OPT4              602
#define IDS_FLAT_MODE_OPT5              603
#define IDS_EJECT_CARD_SIDE_OPT1        604
#define IDS_EJECT_CARD_SIDE_OPT2        605
#define IDS_EJECT_CARD_SIDE_OPT3        606
#define IDS_ERASE_PASS0                 607
#define IDS_ERASE_PASS1                 608
#define IDS_ERASE_PASS2                 609
#define IDS_ERASE_PASS3                 610
#define IDS_ERASE_PASS4                 611
#define IDS_ERASE_PASS5                 612
#define IDS_ERASE_PASS6                 613
#define IDS_RIBBON_ERASE_MODE_OPT1      614
#define IDS_RIBBON_ERASE_MODE_OPT2      615
#define IDS_RIBBON_ERASE_MODE_OPT3      616
#define IDS_PRINT_ACTION_SEQUENCE_OPT1  617
#define IDS_PRINT_ACTION_SEQUENCE_OPT2  618
#define IDS_SECURITY_MODE0              619
#define IDS_SECURITY_MODE1              620
#define IDS_DEFAULT                     621
#define IDC_RADIO1                      801
#define IDC_RADIO2                      802
#define IDC_COMBO_PRINTER               803
#define IDC_COMBO_SYMLINK               804
#define IDC_TAB1                        805
#define IDC_BTN_MOVE_CARD               806
#define IDC_COMBO_CARD_POS              807
#define IDC_STATIC_SDK_VERSION          808
#define IDC_CHECK_LOG                   1001
#define IDC_BTN_GET_PRINTER_INFO        1002
#define IDC_COMBO_INFO_TYPE             1003
#define IDC_BTN_EXECUTE_COMMAND         1004
#define IDC_COMBO_COMMAND               1005
#define IDC_STATIC_ERASE_PARTIAL_CARD   1006
#define IDC_EDIT_ERASE_IMAGE            1007
#define IDC_BTN_BROWSE_ERASE_IMAGE      1008
#define IDC_BTN_ERASE_PARTIAL_CARD      1009
#define IDC_BTN_GET_PRINTER_STAUTS      1010
#define IDC_BTN_GET_PRINTER_WARNING     1011
#define IDC_BTN_SET_STANDBY_PARAM       1012
#define IDC_EDIT_STANDBY_POS            1013
#define IDC_EDIT_STANDBY_TIME           1014
#define IDC_COMBO_STANDBY_SIDE          1015
#define IDC_EDIT_FW_FILE                1016
#define IDC_BTN_BROWSE_FW_FILE          1017
#define IDC_BTN_UPDATE_FIRMWARE         1018
#define IDC_BTN_GET_BIN_FIRMWARE_VERSION 1019
#define IDC_EDIT_BIN_FW_VER             1020
#define IDC_CHECK_AUTO_DETECT_RIBBON    2001
#define IDC_COMBO_RIBBON_TYPE           2002
#define IDC_COMBO_ORIENTATION           2003
#define IDC_COMBO_RESOLUTION            2004
#define IDC_CHECK_PRINT_FRONT           2005
#define IDC_COMBO_FRONT_PANEL           2006
#define IDC_COMBO_FRONT_K_METHOD        2007
#define IDC_CHECK_ROTATE180_FRONT       2008
#define IDC_CHECK_MIRROR_FRONT          2009
#define IDC_CHECK_SECURITY_BMP_FRONT    2010
#define IDC_EDIT_SECURITY_BMP_FRONT     2011
#define IDC_BTN_BROWSE_SECURITY_BMP_FRONT 2012
#define IDC_CHECK_PRINT_BACK            2013
#define IDC_COMBO_BACK_PANEL            2014
#define IDC_COMBO_BACK_K_METHOD         2015
#define IDC_CHECK_ROTATE180_BACK        2016
#define IDC_CHECK_MIRROR_BACK           2017
#define IDC_CHECK_SECURITY_BMP_BACK     2018
#define IDC_EDIT_SECURITY_BMP_BACK      2019
#define IDC_BTN_BROWSE_SECURITY_BMP_BACK 2020
#define IDC_EDIT_IMG_FRONT              2021
#define IDC_BTN_BROWSE                  2022
#define IDC_EDIT_IMG_BACK               2023
#define IDC_BTN_BROWSE2                 2024
#define IDC_EDIT_IMG_FRONT_K            2025
#define IDC_BTN_BROWSE_K                2026
#define IDC_EDIT_IMG_BACK_K             2027
#define IDC_BTN_BROWSE_K2               2028
#define IDC_BTN_PRINT                   2029
#define IDC_BTN_SIMPLE_PRINT            2030
#define IDC_EDIT_TEXT_FRONT             2031
#define IDC_EDIT_TEXT_X                 2032
#define IDC_EDIT_TEXT_Y                 2033
#define IDC_EDIT_IMG_X                  2034
#define IDC_EDIT_IMG_Y                  2035
#define IDC_EDIT_IMG_WIDTH              2036
#define IDC_EDIT_IMG_HEIGHT             2037
#define IDC_EDIT_FONT_NAME              2038
#define IDC_EDIT_FONT_SIZE              2039
#define IDC_EDIT_TEXT_BACK              2040
#define IDC_EDIT_TEXT_X2                2041
#define IDC_EDIT_TEXT_Y2                2042
#define IDC_EDIT_FONT_NAME2             2043
#define IDC_EDIT_IMG_X2                 2044
#define IDC_EDIT_IMG_Y2                 2045
#define IDC_EDIT_IMG_WIDTH2             2046
#define IDC_EDIT_IMG_HEIGHT2            2047
#define IDC_EDIT_FONT_SIZE2             2048
#define IDC_CHECK_ERASE_BEFORE_PRINT    2049
#define IDC_CHECK_MONO_SPEED            2050
#define IDC_CHECK_USE_DEVICE_DEFAULT_CARD_IN_OUT 2051
#define IDC_COMBO_FEED_CARD             2052
#define IDC_COMBO_EJECT_CARD            2053
#define IDC_CHECK_WAIT_FOR_REMOVAL      2054
#define IDC_CHECK_HOOK_MODE             2055
#define IDC_CHECK_RETRY_BY_HOOK_MODE    2056
#define IDC_BTN_GET_PRINTER_SETTING     2057
#define IDC_BTN_SET_PRINTER_SETTING     2058
#define IDC_EDIT_IMG_K_X                2059
#define IDC_EDIT_IMG_K_Y                2060
#define IDC_EDIT_IMG_K_WIDTH            2061
#define IDC_EDIT_IMG_K_HEIGHT           2062
#define IDC_EDIT_IMG_K_X2               2063
#define IDC_EDIT_IMG_K_Y2               2064
#define IDC_EDIT_IMG_K_WIDTH2           2065
#define IDC_EDIT_IMG_K_HEIGHT2          2066
#define IDC_STATIC_PRINT_AREA           2067
#define IDC_COMBO_FRONT_AREA_YMCO       2068
#define IDC_COMBO_FRONT_AREA_K          2069
#define IDC_COMBO_BACK_AREA_YMCO        2070
#define IDC_COMBO_BACK_AREA_K           2071
#define IDC_COMBO_FRONT_AREA_REWRITE    2072
#define IDC_STATIC_PRINT_AREA_FRONT     2073
#define IDC_STATIC_PRINT_AREA_BACK      2074
#define IDC_STATIC_AREA_TAG_YMCO_FRONT  2075
#define IDC_STATIC_AREA_TAG_K_FRONT     2076
#define IDC_STATIC_AREA_TAG_REWRITE_FRONT 2077
#define IDC_STATIC_AREA_TAG_YMCO_BACK   2078
#define IDC_STATIC_AREA_TAG_K_BACK      2079
#define IDC_BTN_GET_PRINT_AREA          2080
#define IDC_BTN_SET_PRINT_AREA          2081
#define IDC_COMBO_PAPER_SIZE            2082
#define IDC_CHECK_GRAY_YMC              2083
#define IDC_BTN_DELETE_ALL_JOBS         2084
#define IDC_CHECK_300X1200              2085
#define IDC_COMBO_PORT                  3001
#define IDC_COMBO_BAUD_RATE             3002
#define IDC_BTN_M1_WRITE_READ           3003
#define IDC_BTN_M1_VALUE                3004
#define IDC_BTN_CPU_TYPE_A              3005
#define IDC_BTN_CPU_TYPE_B              3006
#define IDC_BTN_MIFARE_DESFIRE          3007
#define IDC_BTN_MIFARE_PLUS             3008
#define IDC_BTN_ULTRA_LIGHT             3009
#define IDC_BTN_ULTRA_LIGHT_C           3010
#define IDC_BTN_4442                    3011
#define IDC_BTN_4428                    3012
#define IDC_BTN_24CXX                   3013
#define IDC_BTN_CPU                     3014
#define IDC_BTN_GET_VER                 3015
#define IDC_BTN_CALIBRATE_SCARD_POS     3016
#define IDC_COMBO_SCARD_TYPE            3017
#define IDC_EDIT_RESULT                 3018
#define IDC_COMBO_COERCIVITY            4001
#define IDC_CHECK_T1                    4002
#define IDC_EDIT_T1                     4003
#define IDC_EDIT_T1R                    4004
#define IDC_CHECK_T2                    4005
#define IDC_EDIT_T2                     4006
#define IDC_EDIT_T2R                    4007
#define IDC_CHECK_T3                    4008
#define IDC_EDIT_T3                     4009
#define IDC_EDIT_T3R                    4010
#define IDC_BTN_ENCODE_TRACKS           4011
#define IDC_BTN_READ_TRACKS             4012
#define IDC_BTN_EJECT_CARD              4013
#define IDC_COMBO_PORT_UHF              5001
#define IDC_BTN_CONNECT                 5002
#define IDC_BTN_DISCONNECT              5003
#define IDC_BTN_READ_EPC                5004
#define IDC_BTN_READ_TID                5005
#define IDC_BTN_READ_DATA               5006
#define IDC_BTN_WRITE_DATA              5007
#define IDC_EDIT_EPC                    5008
#define IDC_EDIT_TID                    5009
#define IDC_EDIT_START_ADDR_TID         5010
#define IDC_EDIT_LENGTH_TID             5011
#define IDC_EDIT_PASSWORD_READ          5012
#define IDC_EDIT_START_ADDR_READ        5013
#define IDC_EDIT_LENGTH_READ            5014
#define IDC_COMBO_SECTION_READ          5015
#define IDC_EDIT_DATA_READ              5016
#define IDC_EDIT_PASSWORD_WRITE         5017
#define IDC_EDIT_START_ADDR_WRITE       5018
#define IDC_COMBO_SECTION_WRITE         5019
#define IDC_EDIT_DATA_WRITE             5020
#define IDC_COMBO_PORT_FM1208           6001
#define IDC_BTN_INIT_CARD               6002
#define IDC_BTN_RECOVER                 6003
#define IDC_EDIT_ID_W                   6004
#define IDC_EDIT_NAME_W                 6005
#define IDC_BTN_WRITE_CARD              6006
#define IDC_EDIT_ID_R                   6007
#define IDC_EDIT_NAME_R                 6008
#define IDC_BTN_READ_CARD               6009
#define IDC_BTN_PRINT_BYPASS_DRIVER     7001
#define IDC_EDIT_PRINT2_COLOR1          7002
#define IDC_EDIT_PRINT2_K1              7003
#define IDC_EDIT_PRINT2_O1              7004
#define IDC_EDIT_PRINT2_ERASE           7005
#define IDC_EDIT_PRINT2_COLOR2          7006
#define IDC_EDIT_PRINT2_K2              7007
#define IDC_EDIT_PRINT2_O2              7008
#define IDC_EDIT_PRINT2_ERASE2          7009
#define IDC_BTN_PRINT2_BROWSE_COLOR1    7010
#define IDC_BTN_PRINT2_BROWSE_K1        7011
#define IDC_BTN_PRINT2_BROWSE_O1        7012
#define IDC_BTN_PRINT2_BROWSE_ERASE     7013
#define IDC_BTN_PRINT2_BROWSE_COLOR2    7014
#define IDC_BTN_PRINT2_BROWSE_K2        7015
#define IDC_BTN_PRINT2_BROWSE_O2        7016
#define IDC_BTN_PRINT2_BROWSE_ERASE2    7017
#define IDC_CHECK_COLOR1                7018
#define IDC_CHECK_K1                    7019
#define IDC_CHECK_O1                    7020
#define IDC_CHECK_ERASE1                7021
#define IDC_CHECK_COLOR2                7022
#define IDC_CHECK_K2                    7023
#define IDC_CHECK_O2                    7024
#define IDC_CHECK_ERASE2                7025
#define IDC_COMBO_ERASE_PASS            7026
#define IDC_EDIT_COLOR1                 7101
#define IDC_EDIT_COLOR2                 7102
#define IDC_EDIT_COLOR3                 7103
#define IDC_EDIT_COLOR4                 7104
#define IDC_EDIT_COLOR5                 7105
#define IDC_EDIT_COLOR6                 7106
#define IDC_EDIT_COLOR7                 7107
#define IDC_EDIT_COLOR8                 7108
#define IDC_SPIN_COLOR1                 7109
#define IDC_SPIN_COLOR2                 7110
#define IDC_SPIN_COLOR3                 7111
#define IDC_SPIN_COLOR4                 7112
#define IDC_SPIN_COLOR5                 7113
#define IDC_SPIN_COLOR6                 7114
#define IDC_SPIN_COLOR7                 7115
#define IDC_SPIN_COLOR8                 7116
#define IDC_EDIT_HEAT_Y1                7201
#define IDC_EDIT_HEAT_K1                7202
#define IDC_EDIT_HEAT_O1                7203
#define IDC_EDIT_HEAT_R1                7204
#define IDC_EDIT_HEAT_Y2                7205
#define IDC_EDIT_HEAT_K2                7206
#define IDC_EDIT_HEAT_O2                7207
#define IDC_EDIT_HEAT_R2                7208
#define IDC_EDIT_HEAT_WRITE             7209
#define IDC_EDIT_HEAT_ERASE             7210
#define IDC_SPIN_HEAT_Y1                7211
#define IDC_SPIN_HEAT_K1                7212
#define IDC_SPIN_HEAT_O1                7213
#define IDC_SPIN_HEAT_R1                7214
#define IDC_SPIN_HEAT_Y2                7215
#define IDC_SPIN_HEAT_K2                7216
#define IDC_SPIN_HEAT_O2                7217
#define IDC_SPIN_HEAT_R2                7218
#define IDC_SPIN_HEAT_WRITE             7219
#define IDC_SPIN_HEAT_ERASE             7220
#define IDC_BTN_READ_CURRENT_CONFIG     8000
#define IDC_BTN_APPLY_NEW_CONFIG        8001
#define IDC_COMBO_CARD_TYPE             8002
#define IDC_EDIT_HEAT_SPEED1            8003
#define IDC_SPIN_HEAT_SPEED1            8004
#define IDC_EDIT_HEAT_TEMP1             8005
#define IDC_SPIN_HEAT_TEMP1             8006
#define IDC_EDIT_HEAT_POS1              8007
#define IDC_SPIN_HEAT_POS1              8008
#define IDC_EDIT_HEAT_SPEED2            8009
#define IDC_SPIN_HEAT_SPEED2            8010
#define IDC_EDIT_HEAT_TEMP2             8011
#define IDC_SPIN_HEAT_TEMP2             8012
#define IDC_EDIT_HEAT_POS2              8013
#define IDC_SPIN_HEAT_POS2              8014
#define IDC_EDIT_HEAT_SPEED3            8015
#define IDC_SPIN_HEAT_SPEED3            8016
#define IDC_EDIT_HEAT_TEMP3             8017
#define IDC_SPIN_HEAT_TEMP3             8018
#define IDC_EDIT_HEAT_POS3              8019
#define IDC_SPIN_HEAT_POS3              8020
#define IDC_EDIT_FLAT_SPEED             8021
#define IDC_SPIN_FLAT_SPEED             8022
#define IDC_COMBO_FLAT_MODE1            8023
#define IDC_COMBO_FLAT_MODE2            8024
#define IDC_COMBO_FLAT_MODE3            8025
#define IDC_COMBO_EJECT_CARD_SIDE       8026
#define IDC_COMBO_RIBBON_ERASE_MODE     8027
#define IDC_COMBO_PRINT_ACTION_SEQUENCE 8028
#define IDC_BTN_GET_CUR_CONFIG          9000
#define IDC_BTN_SET_NEW_CONFIG          9001
#define IDC_STATIC_ADF_TAG              9002
#define IDC_CHECK_CARD_OUT_SENSOR       9003
#define IDC_CHECK_HOOK_MODE2            9004
#define IDC_CHECK_RETRY_BY_HOOK_MODE2   9005
#define IDC_STATIC_EJECT_CARD1          9006
#define IDC_COMBO_EJECT_CARD1           9007
#define IDC_STATIC_BACK_END_TAG         9008
#define IDC_CHECK_AUTO_FEED_M1          9009
#define IDC_STATIC_EJECT_CARD2          9010
#define IDC_COMBO_EJECT_CARD2           9011
#define IDC_STATIC_FRONT_END_TAG        9012
#define IDC_CHECK_AUTO_FEED_M2          9013
#define IDC_STATIC_EJECT_CARD3          9014
#define IDC_COMBO_EJECT_CARD3           9015
#define IDC_STATIC_DOWN_END_TAG         9016
#define IDC_CHECK_AUTO_FEED_M3          9017
#define IDC_STATIC_EJECT_CARD4          9018
#define IDC_COMBO_EJECT_CARD4           9019
#define IDC_STATIC_AUTO_EJECT_CARD_TAG  9020
#define IDC_CHECK_AUTO_EJECT_CARD       9021
#define IDC_STATIC_EJECT_CARD5          9022
#define IDC_COMBO_EJECT_CARD5           9023
#define IDC_STATIC_EJECT_CARD_TAG       9024
#define IDC_STATIC_EXIT1                9025
#define IDC_CHECK_WAIT_FOR_REMOVAL_E1   9026
#define IDC_STATIC_WAIT_CARD_POS_TAG    9027
#define IDC_EDIT_WAIT_CARD_POS          9028
#define IDC_STATIC_WAIT_CARD_MM         9029
#define IDC_STATIC_WAIT_CARD_TIME_TAG   9030
#define IDC_EDIT_WAIT_CARD_TIME         9031
#define IDC_STATIC_WAIT_CARD_MS         9032
#define IDC_STATIC_EXIT2                9033
#define IDC_CHECK_WAIT_FOR_REMOVAL_E2   9034
#define IDC_STATIC_WAIT_CARD_POS_TAG2   9035
#define IDC_EDIT_WAIT_CARD_POS2         9036
#define IDC_STATIC_WAIT_CARD_MM2        9037
#define IDC_STATIC_WAIT_CARD_TIME_TAG2  9038
#define IDC_EDIT_WAIT_CARD_TIME2        9039
#define IDC_STATIC_WAIT_CARD_MS2        9040
#define IDC_STATIC_EXIT3                9041
#define IDC_CHECK_WAIT_FOR_REMOVAL_E3   9042
#define IDC_STATIC_WAIT_CARD_POS_TAG3   9043
#define IDC_EDIT_WAIT_CARD_POS3         9044
#define IDC_STATIC_WAIT_CARD_MM3        9045
#define IDC_STATIC_WAIT_CARD_TIME_TAG3  9046
#define IDC_EDIT_WAIT_CARD_TIME3        9047
#define IDC_STATIC_WAIT_CARD_MS3        9048
#define IDC_STATIC_DEFAULT_USE          9049
#define IDC_COMBO_FEED_CARD_DEFAULT     9050
#define IDC_COMBO_REJECT_CARD_DEFAULT   9051
#define IDC_STATIC_FEED_CARD            9052
#define IDC_STATIC_REJECT_CARD          9053
#define IDC_STATIC_DEFAULT_USE_CLEAN    9054
#define IDC_STATIC_FEED_CARD_CLEAN      9055
#define IDC_COMBO_FEED_CARD_CLEAN       9056
#define IDC_STATIC_EJECT_CARD_CLEAN     9057
#define IDC_COMBO_EJECT_CARD_CLEAN      9058
#define IDC_EDIT_L                      9100
#define IDC_SPIN_L                      9101
#define IDC_EDIT_T                      9102
#define IDC_SPIN_T                      9103
#define IDC_EDIT_S                      9104
#define IDC_SPIN_S                      9105
#define IDC_BTN_SET_PRINT_POS           9106
#define IDC_BTN_GET_PRINT_POS           9107
#define IDC_BTN_PRINT_POS_CHART         9108
#define IDC_EDIT_IC_POS                 9109
#define IDC_SPIN_IC_POS                 9110
#define IDC_BTN_SET_IC_POS              9111
#define IDC_BTN_SET_RF_POS              9112
#define IDC_EDIT_RF_POS                 9113
#define IDC_SPIN_RF_POS                 9114
#define IDC_BTN_GET_IC_POS              9115
#define IDC_BTN_GET_RF_POS              9116
#define IDC_CHECK_REJECT_BOX_COVER      9200
#define IDC_CHECK_REJECT_BOX_FULL       9201
#define IDC_COMBO_CARD_IN_SIGNAL        9202
#define IDC_COMBO_INIT_RIBBON_MODE      9203
#define IDC_BTN_SET_OTHER_CONFIG_VALUE  9204
#define IDC_BTN_GET_OTHER_CONFIG_VALUE  9205
#define IDC_COMBO_CONCAVE_SIDE          9504
#define IDC_EDIT_CONCAVE_DISTANCE       9505
#define IDC_SPIN_CONCAVE_DISTANCE       9506
#define IDC_EDIT_CONCAVE_SPACE          9507
#define IDC_SPIN_CONCAVE_SPACE          9508
#define IDC_EDIT_CONCAVE_DIGITS         9509
#define IDC_BTN_CONCAVE_PRINT           9510
#define IDC_BTN_CALIBRATE_RIBBON_LED    9511
#define IDC_BTN_READ_RIBBON_LED_VALUE   9512
#define IDC_EDIT_RIBBON_LED_VALUE       9513
#define IDC_EDIT_CONCAVE_FW_VER         9514
#define IDC_BTN_GET_CONCAVE_FW_VER      9515
#define IDC_BTN_GET_CONCAVE_SERIAL      9516
#define IDC_BTN_GET_CONCAVE_REMAIN_RIBBON 9517
#define IDC_EDIT_CONCAVE_SERIAL         9518
#define IDC_EDIT_CONCAVE_REMAIN_RIBBON  9519
#define IDC_EDIT_DIGIT0                 9522
#define IDC_SPIN_DIGIT0                 9523
#define IDC_EDIT_DIGIT1                 9524
#define IDC_SPIN_DIGIT1                 9525
#define IDC_EDIT_DIGIT2                 9526
#define IDC_SPIN_DIGIT2                 9527
#define IDC_EDIT_DIGIT3                 9528
#define IDC_SPIN_DIGIT3                 9529
#define IDC_EDIT_DIGIT4                 9530
#define IDC_SPIN_DIGIT4                 9531
#define IDC_EDIT_DIGIT5                 9532
#define IDC_SPIN_DIGIT5                 9533
#define IDC_EDIT_DIGIT6                 9534
#define IDC_SPIN_DIGIT6                 9535
#define IDC_EDIT_DIGIT7                 9536
#define IDC_SPIN_DIGIT7                 9537
#define IDC_EDIT_DIGIT8                 9538
#define IDC_SPIN_DIGIT8                 9539
#define IDC_EDIT_DIGIT9                 9540
#define IDC_SPIN_DIGIT9                 9541
#define IDC_BTN_GET_HAMMER_PARAM        9542
#define IDC_BTN_SET_HAMMER_PARAM        9543
#define IDC_EDIT_DIGIT10                9544
#define IDC_SPIN_DIGIT10                9545
#define IDC_EDIT_DIGIT11                9546
#define IDC_SPIN_DIGIT11                9547
#define IDC_EDIT_DIGIT12                9548
#define IDC_SPIN_DIGIT12                9549
#define IDC_EDIT_DIGIT13                9550
#define IDC_SPIN_DIGIT13                9551
#define IDC_EDIT_DIGIT14                9552
#define IDC_SPIN_DIGIT14                9553
#define IDC_EDIT_DIGIT15                9554
#define IDC_SPIN_DIGIT15                9555
#define IDC_EDIT_DIGIT16                9556
#define IDC_SPIN_DIGIT16                9557
#define IDC_EDIT_DIGIT17                9558
#define IDC_SPIN_DIGIT17                9559
#define IDC_EDIT_DIGIT18                9560
#define IDC_SPIN_DIGIT18                9561
#define IDC_EDIT_DIGIT19                9562
#define IDC_SPIN_DIGIT19                9563
#define IDC_BTN_GET_DISK_COMP_PARAM     9564
#define IDC_BTN_SET_DISK_COMP_PARAM     9565
#define IDC_CHECK_PRINT_CONCAVE         9566
#define IDC_BTN_SET_SECURITY_MODE       9567
#define IDC_EDIT_CUR_PASSWD             9568
#define IDC_COMBO_SECURITY_MODE         9569
#define IDC_BTN_SET_SECURITY_PASSWORD   9570
#define IDC_EDIT_OLD_PASSWD             9571
#define IDC_EDIT_NEW_PASSWD             9572
#define IDC_EDIT_INDENT_FW_FILE         9573
#define IDC_BTN_BROWSE_INDENT_FW_BIN    9574
#define IDC_BTN_UPDATE_INDENT_FIRMWARE  9575

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         9576
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
