//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace luo.dangxiao.resources.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("luo.dangxiao.resources.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Self Service 的本地化字符串。
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string Label_Time {
            get {
                return ResourceManager.GetString("Label_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this item? 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred 的本地化字符串。
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string Msg_Loading {
            get {
                return ResourceManager.GetString("Msg_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provider &quot;{0}&quot; in config.json is invalid. The application has fallen back to {1}. 的本地化字符串。
        /// </summary>
        public static string Msg_PrinterProviderFallback {
            get {
                return ResourceManager.GetString("Msg_PrinterProviderFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation completed successfully 的本地化字符串。
        /// </summary>
        public static string Msg_Success {
            get {
                return ResourceManager.GetString("Msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Nav_About {
            get {
                return ResourceManager.GetString("Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self-service Check-in 的本地化字符串。
        /// </summary>
        public static string SelfService_CheckIn {
            get {
                return ResourceManager.GetString("SelfService_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check-in 的本地化字符串。
        /// </summary>
        public static string SelfService_CheckIn_Button_Action {
            get {
                return ResourceManager.GetString("SelfService_CheckIn_Button_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have successfully checked in. 的本地化字符串。
        /// </summary>
        public static string SelfService_CheckIn_Title_CheckedIn {
            get {
                return ResourceManager.GetString("SelfService_CheckIn_Title_CheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm your information, then click [Check-in] to complete check-in. 的本地化字符串。
        /// </summary>
        public static string SelfService_CheckIn_Title_NotCheckedIn {
            get {
                return ResourceManager.GetString("SelfService_CheckIn_Title_NotCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Information 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_BasicInfo {
            get {
                return ResourceManager.GetString("SelfService_Info_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Card Expiry Date 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_CardExpiryDate {
            get {
                return ResourceManager.GetString("SelfService_Info_CardExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Card Type 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_CardType {
            get {
                return ResourceManager.GetString("SelfService_Info_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check-in Room 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_CheckInRoom {
            get {
                return ResourceManager.GetString("SelfService_Info_CheckInRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check-in Time 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_CheckInTime {
            get {
                return ResourceManager.GetString("SelfService_Info_CheckInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class Name 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_ClassName {
            get {
                return ResourceManager.GetString("SelfService_Info_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consumption Balance 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_ConsumptionBalance {
            get {
                return ResourceManager.GetString("SelfService_Info_ConsumptionBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_Department {
            get {
                return ResourceManager.GetString("SelfService_Info_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_Name {
            get {
                return ResourceManager.GetString("SelfService_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_RangeSeparator {
            get {
                return ResourceManager.GetString("SelfService_Info_RangeSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff Number 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_StaffNumber {
            get {
                return ResourceManager.GetString("SelfService_Info_StaffNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subsidy Balance 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_SubsidyBalance {
            get {
                return ResourceManager.GetString("SelfService_Info_SubsidyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Training Time 的本地化字符串。
        /// </summary>
        public static string SelfService_Info_TrainingTime {
            get {
                return ResourceManager.GetString("SelfService_Info_TrainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self-service Query 的本地化字符串。
        /// </summary>
        public static string SelfService_Query {
            get {
                return ResourceManager.GetString("SelfService_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self-service Recharge 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge {
            get {
                return ResourceManager.GetString("SelfService_Recharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ￥100 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_Amount_100 {
            get {
                return ResourceManager.GetString("SelfService_Recharge_Amount_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ￥20 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_Amount_20 {
            get {
                return ResourceManager.GetString("SelfService_Recharge_Amount_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ￥200 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_Amount_200 {
            get {
                return ResourceManager.GetString("SelfService_Recharge_Amount_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ￥50 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_Amount_50 {
            get {
                return ResourceManager.GetString("SelfService_Recharge_Amount_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ￥500 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_Amount_500 {
            get {
                return ResourceManager.GetString("SelfService_Recharge_Amount_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select recharge amount 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_AmountSelectionTitle {
            get {
                return ResourceManager.GetString("SelfService_Recharge_AmountSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please complete the payment on your phone and return to this device to confirm. 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_QRCode_Instruction {
            get {
                return ResourceManager.GetString("SelfService_Recharge_QRCode_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please use WeChat/Alipay to scan the QR code 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_QRCode_ScanHint {
            get {
                return ResourceManager.GetString("SelfService_Recharge_QRCode_ScanHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount pending payment: ¥{0:0.##} 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_Status_PendingPayment {
            get {
                return ResourceManager.GetString("SelfService_Recharge_Status_PendingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please confirm your information, then select an amount to recharge. 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_Title_Confirm {
            get {
                return ResourceManager.GetString("SelfService_Recharge_Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm the amount, then scan the QR code to complete payment. 的本地化字符串。
        /// </summary>
        public static string SelfService_Recharge_Title_QRCode {
            get {
                return ResourceManager.GetString("SelfService_Recharge_Title_QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self-service Card Replacement 的本地化字符串。
        /// </summary>
        public static string SelfService_Replacement {
            get {
                return ResourceManager.GetString("SelfService_Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self-service Loss Report 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Loss 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Button_Action {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Button_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}s 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Countdown_Format {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Countdown_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to report the card loss. 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Status_Failed {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The YktApi service is not configured. Please check the YktApiConfig settings. 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Status_Failed_ApiUnavailable {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Status_Failed_ApiUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The loss report was cancelled because the page countdown expired. 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Status_Failed_CountdownCancelled {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Status_Failed_CountdownCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required report loss parameters are incomplete: {0}. 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Status_Failed_InvalidConfig {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Status_Failed_InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No card number was found, so the card cannot be reported lost. 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Status_Failed_NoCardNumber {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Status_Failed_NoCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The loss report request timed out. Please try again. 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Status_Failed_Timeout {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Status_Failed_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to report the card loss: {0} 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Status_Failed_WithReason {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Status_Failed_WithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submitting the loss report, please wait... 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Status_Processing {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Status_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The card has been reported lost successfully. 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Status_Success {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Status_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have a normal card, or your card is already reported lost and cannot be reported again. 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Title_Invalid {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Title_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After confirming your information, click [Report Loss] to proceed. 的本地化字符串。
        /// </summary>
        public static string SelfService_ReportLoss_Title_Normal {
            get {
                return ResourceManager.GetString("SelfService_ReportLoss_Title_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self-service Card Pickup 的本地化字符串。
        /// </summary>
        public static string SelfService_TakeCard {
            get {
                return ResourceManager.GetString("SelfService_TakeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete 的本地化字符串。
        /// </summary>
        public static string SelfService_TakeCard_Button_Complete {
            get {
                return ResourceManager.GetString("SelfService_TakeCard_Button_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Card Pickup 的本地化字符串。
        /// </summary>
        public static string SelfService_TakeCard_Button_Confirm {
            get {
                return ResourceManager.GetString("SelfService_TakeCard_Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Card Collected 的本地化字符串。
        /// </summary>
        public static string SelfService_TakeCard_Button_PickedUp {
            get {
                return ResourceManager.GetString("SelfService_TakeCard_Button_PickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This card has been reported lost, please use self-service replacement 的本地化字符串。
        /// </summary>
        public static string SelfService_TakeCard_Title_Lost {
            get {
                return ResourceManager.GetString("SelfService_TakeCard_Title_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current card status is normal, no replacement is needed 的本地化字符串。
        /// </summary>
        public static string SelfService_TakeCard_Title_Normal {
            get {
                return ResourceManager.GetString("SelfService_TakeCard_Title_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No card collection is required for your account 的本地化字符串。
        /// </summary>
        public static string SelfService_TakeCard_Title_Other {
            get {
                return ResourceManager.GetString("SelfService_TakeCard_Title_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please confirm your information before collecting the card 的本地化字符串。
        /// </summary>
        public static string SelfService_TakeCard_Title_PendingPickup {
            get {
                return ResourceManager.GetString("SelfService_TakeCard_Title_PendingPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID Card Verification 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_IDCard {
            get {
                return ResourceManager.GetString("SelfService_Verify_IDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification failed 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_IDCardFailed {
            get {
                return ResourceManager.GetString("SelfService_Verify_IDCardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please place your ID card on the sensing area 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_IDCardInstruction {
            get {
                return ResourceManager.GetString("SelfService_Verify_IDCardInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing card information, please wait... 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_IDCardProcessing {
            get {
                return ResourceManager.GetString("SelfService_Verify_IDCardProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification succeeded 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_IDCardSuccess {
            get {
                return ResourceManager.GetString("SelfService_Verify_IDCardSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for ID card reading... 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_IDCardWaiting {
            get {
                return ResourceManager.GetString("SelfService_Verify_IDCardWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID Card Sensing Area 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_IDCardZoneTitle {
            get {
                return ResourceManager.GetString("SelfService_Verify_IDCardZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select verification method 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SelectMethod {
            get {
                return ResourceManager.GetString("SelfService_Verify_SelectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS Verification 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SMS {
            get {
                return ResourceManager.GetString("SelfService_Verify_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification Code 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SMS_Code {
            get {
                return ResourceManager.GetString("SelfService_Verify_SMS_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter verification code 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SMS_CodePlaceholder {
            get {
                return ResourceManager.GetString("SelfService_Verify_SMS_CodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SMS_Next {
            get {
                return ResourceManager.GetString("SelfService_Verify_SMS_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone Number 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SMS_Phone {
            get {
                return ResourceManager.GetString("SelfService_Verify_SMS_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter phone number 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SMS_PhonePlaceholder {
            get {
                return ResourceManager.GetString("SelfService_Verify_SMS_PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resend [0]s 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SMS_Resend {
            get {
                return ResourceManager.GetString("SelfService_Verify_SMS_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Verification Code 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SMS_SendCode {
            get {
                return ResourceManager.GetString("SelfService_Verify_SMS_SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS Verification 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SMS_Title {
            get {
                return ResourceManager.GetString("SelfService_Verify_SMS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to ID Card Verification → 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SwitchToIDCard {
            get {
                return ResourceManager.GetString("SelfService_Verify_SwitchToIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to SMS Verification → 的本地化字符串。
        /// </summary>
        public static string SelfService_Verify_SwitchToSMS {
            get {
                return ResourceManager.GetString("SelfService_Verify_SwitchToSMS", resourceCulture);
            }
        }
    }
}
