// <auto-generated>
// Seaory SDK Constants - Ported from SeaoryPrinter.h
// SDK Version: 1.6.4.0
// </auto-generated>

using System;

namespace luo.dangxiao.printer.Seaory.Native
{
    /// <summary>
    /// Commands used for SOY_PR_ExecCommand()
    /// </summary>
    public static class PrinterCommand
    {
        /// <summary>Move Card to Output Hopper</summary>
        public const uint MoveCardToHopper = 1;
        /// <summary>Move Card to Contact Encoder Station</summary>
        public const uint MoveCardToContact = 2;
        /// <summary>Move Card to Contactless Encoder Station</summary>
        public const uint MoveCardToContactless = 3;
        /// <summary>Move Card to Standby (back)</summary>
        public const uint MoveCardToStandbyBack = 4;
        /// <summary>Move Card to Flipper</summary>
        public const uint MoveCardToFlipper = 5;
        /// <summary>Move Card to Reject Box (front)</summary>
        public const uint MoveCardToRejectBoxFront = 6;
        /// <summary>Move Card to Reject Box (down)</summary>
        public const uint MoveCardToRejectBoxDown = 7;
        /// <summary>Move Card to Standby (front)</summary>
        public const uint MoveCardToStandbyFront = 8;
        /// <summary>Move Card to Front position</summary>
        public const uint MoveCardToFront = 9;
        /// <summary>Move Card to Prepare position</summary>
        public const uint MoveCardToPrepare = 10;
        /// <summary>Move Card to Indent-Printing module</summary>
        public const uint MoveCardToIndentPrinter = 11;
        /// <summary>Move Card to Standby (down)</summary>
        public const uint MoveCardToStandbyDown = 12;
        /// <summary>Move card to storage card position</summary>
        public const uint MoveCardToStorage = 13;
        /// <summary>Storage card position to prepare position</summary>
        public const uint MoveCardFromStorageToPrepare = 14;

        /// <summary>Hard reset printer, printer status and temporary setting will be lost.</summary>
        public const uint ResetPrinterHard = 21;
        /// <summary>Card jam reset, the card will move to prepare position and will finish initialize flow.</summary>
        public const uint ResetPrinterJam = 22;
        /// <summary>Clean card path</summary>
        public const uint CleanCardPath = 23;
        /// <summary>Flip card then move card to prepare position</summary>
        public const uint FlipCard = 24;
        /// <summary>Clean card path, after finished, do not eject card.</summary>
        public const uint CleanCardPathNoEject = 25;
        /// <summary>Move ribbon for length unit is mm.</summary>
        public const uint MoveRibbon = 26;
        /// <summary>Rotate flipper to initial position.</summary>
        public const uint InitializeFlipper = 27;
        /// <summary>Calibrate ribbon LED</summary>
        public const uint CalibrateRibbonLed = 28;
        /// <summary>Clean card path, adjust ribbon motor when cleaning.</summary>
        public const uint CleanCardPathAdjRbnMtr = 29;

        /// <summary>Erase rewritable card whole card</summary>
        public const uint EraseFullCard = 31;

        /// <summary>Cancel suspended task</summary>
        public const uint CancelSuspendedTask = 50;
    }

    /// <summary>
    /// Info types used for SOY_PR_GetPrinterInfo()
    /// </summary>
    public static class PrinterInfoType
    {
        /// <summary>Printer model name</summary>
        public const int ModelName = 1;
        /// <summary>Printer firmware version</summary>
        public const int FirmwareVersion = 2;
        /// <summary>Printer serial number</summary>
        public const int SerialNumber = 3;
        /// <summary>Current card position in printer</summary>
        public const int CardPosition = 4;
        /// <summary>Current installed ribbon type</summary>
        public const int RibbonType = 5;
        /// <summary>Current installed ribbon remain count</summary>
        public const int RibbonCount = 6;
        /// <summary>Printed count by frames</summary>
        public const int PrintCount = 7;
        /// <summary>Region code</summary>
        public const int RegionCode = 8;
        /// <summary>Unclean count</summary>
        public const int UncleanCount = 9;
        /// <summary>Current installed modules</summary>
        public const int InstalledModule = 10;
        /// <summary>Current status of front reject box</summary>
        public const int RejectBoxStatus = 11;
        /// <summary>Current status of card out status</summary>
        public const int CardOutStatus = 12;
        /// <summary>Current installed film remain count</summary>
        public const int FilmCount = 13;
        /// <summary>Ethernet MAC address</summary>
        public const int MacAddress = 14;
        /// <summary>Current ribbon chip UID</summary>
        public const int RibbonChipUid = 15;
        /// <summary>Current film chip UID</summary>
        public const int FilmChipUid = 16;
        /// <summary>Current status of storage position</summary>
        public const int StorageStatus = 17;
        /// <summary>Current installed ribbon original count</summary>
        public const int RibbonCountOrg = 18;
        /// <summary>Current security mode</summary>
        public const int SecurityMode = 19;
        /// <summary>Ribbon LED value</summary>
        public const int RibbonLedValue = 20;
        /// <summary>Magnetic count</summary>
        public const int MagneticCount = 21;
        /// <summary>Contact count</summary>
        public const int ContactCount = 22;
        /// <summary>Contactless count</summary>
        public const int ContactlessCount = 23;
        /// <summary>Printer driver version</summary>
        public const int DriverVersion = 24;

        /// <summary>Indent-printing module firmware version</summary>
        public const int IndentPrinterFwVersion = 30;
        /// <summary>Indent-printing module serial number</summary>
        public const int IndentPrinterSerial = 31;
        /// <summary>Indent-printing module remain ribbon count</summary>
        public const int IndentPrinterRibbonRemain = 32;
    }

    /// <summary>
    /// Card position values returned by INFO_CARD_POSITION
    /// </summary>
    public static class CardPosition
    {
        public const int OutOfPrinter = 0;
        public const int FrontStandby = 3;
        public const int Flipper = 4;
        public const int MagIn = 5;
        public const int MagOut = 6;
        public const int StartPrinting = 7;
        public const int PrintEnd = 8;
        public const int Contact = 9;
        public const int Contactless = 10;
        public const int BackStandby = 11;
        public const int CardJamPos = 12;
        public const int PreparePos = 13;
        public const int StartPrinting2 = 15;
        public const int DownStandby = 17;
        public const int WaitEmboss = 18;
    }

    /// <summary>
    /// Flags of installed module for return value of INFO_INSTALLED_MODULE
    /// </summary>
    [Flags]
    public enum InstalledModuleFlags : uint
    {
        None = 0,
        Flipper = 0x00000001,
        MagStripe = 0x00000002,
        ContactIC = 0x00000004,
        RFID = 0x00000008,
        Ethernet = 0x00000010,
        Indent = 0x00000040,
        Dpi600 = 0x00010000,
        RibbonSecurity = 0x00020000,
        PrinterSecurity = 0x00040000,
        Rewrite = 0x00080000
    }

    /// <summary>
    /// Configuration types used for SOY_PR_SetPrinterConfig() and SOY_PR_GetPrinterConfig()
    /// </summary>
    public static class PrinterConfigType
    {
        /// <summary>Front end manual feed slot</summary>
        public const uint ManualFeedFront = 1;
        /// <summary>Back end manual feed slot</summary>
        public const uint ManualFeedBack = 2;
        /// <summary>Input bin to be used</summary>
        public const uint InputBin = 3;
        /// <summary>ADF to use hook mode or not</summary>
        public const uint AdfHookMode = 4;
        /// <summary>Output bin to be used and its mode</summary>
        public const uint OutputBinMode = 5;
        /// <summary>Target output bin when use the selected input bin</summary>
        public const uint InputOutputBinding = 6;
        /// <summary>Smart card reader card-in signal level</summary>
        public const uint CardInSignal = 7;
        /// <summary>Reject box sensor detection mode</summary>
        public const uint RejectBoxSensor = 8;
        /// <summary>Card out sensor detection mode</summary>
        public const uint CardOutSensor = 9;
        /// <summary>Reject bin to be used</summary>
        public const uint RejectBin = 10;
        /// <summary>Initial ribbon mode</summary>
        public const uint InitialRibbonMode = 11;
        /// <summary>Position of moving card to contact encoder</summary>
        public const uint IcCardPos = 12;
        /// <summary>Position of moving card to contactless encoder</summary>
        public const uint RfCardPos = 13;

        /// <summary>Offset of printing card leading edge</summary>
        public const uint PrintPosL = 14;
        /// <summary>Offset of printing card tailing edge</summary>
        public const uint PrintPosT = 15;
        /// <summary>Offset of printing card side edge</summary>
        public const uint PrintPosS = 16;

        /// <summary>Standby parameters of front end</summary>
        public const uint StandbyFrontEnd = 17;
        /// <summary>Standby parameters of back end</summary>
        public const uint StandbyBackEnd = 18;

        /// <summary>Auto eject card when power on or hard reset printer</summary>
        public const uint AutoEjectAtInit = 19;
        /// <summary>Output bin to be used for auto eject card</summary>
        public const uint AutoEjectOutputBin = 20;

        /// <summary>Down end manual feed slot</summary>
        public const uint ManualFeedDown = 21;
        /// <summary>Standby parameters of down end</summary>
        public const uint StandbyDownEnd = 22;

        // Retransfer printer only
        /// <summary>Retransfer parameters group to be used. Default is 0. Range is 0~3</summary>
        public const uint RtrCardType = 101;
        /// <summary>Retransfer speed of user defined 1. Default is 0. Range is -10~+10</summary>
        public const uint RtrUser1Speed = 102;
        /// <summary>Retransfer temperature of user defined 1. Default is 0. Range is -11~+7</summary>
        public const uint RtrUser1Temperature = 103;
        /// <summary>Retransfer offset of user defined 1. Default is 0. Range is 0~10</summary>
        public const uint RtrUser1Offset = 104;
        /// <summary>Retransfer speed of user defined 2</summary>
        public const uint RtrUser2Speed = 105;
        /// <summary>Retransfer temperature of user defined 2</summary>
        public const uint RtrUser2Temperature = 106;
        /// <summary>Retransfer offset of user defined 2</summary>
        public const uint RtrUser2Offset = 107;
        /// <summary>Retransfer speed of user defined 3</summary>
        public const uint RtrUser3Speed = 108;
        /// <summary>Retransfer temperature of user defined 3</summary>
        public const uint RtrUser3Temperature = 109;
        /// <summary>Retransfer offset of user defined 3</summary>
        public const uint RtrUser3Offset = 110;

        /// <summary>Ribbon erase mode</summary>
        public const uint RtrRibbonEraseMode = 150;
        /// <summary>Print action sequence</summary>
        public const uint RtrPrintActionSeq = 151;

        /// <summary>Indent-printing module hammer parameters</summary>
        public const uint IndentHammerParam = 201;
        /// <summary>Indent-printing module disk digit compensation parameters</summary>
        public const uint IndentDiskCompParam = 202;
    }

    /// <summary>
    /// Ribbon types for S series printers
    /// </summary>
    public enum RibbonTypeS : byte
    {
        YMCKO = 0,
        K = 1,
        HalfYmcko = 2,
        YMCKOK = 3,
        KO = 4,
        Gold = 5,
        Silver = 6,
        White = 7,
        HalfYmcKoko = 8,
        HalfYmckoN = 9,
        RYMCK = 10,
        UV = 11,
        Red = 12,
        Blue = 13
    }

    /// <summary>
    /// Ribbon types for R series printers
    /// </summary>
    public enum RibbonTypeR : byte
    {
        YMCK = 100,
        YMCKK = 101,
        K = 1
    }

    /// <summary>
    /// Print side selection
    /// </summary>
    [Flags]
    public enum PrintSide : byte
    {
        None = 0x00,
        Front = 0x01,
        Back = 0x10,
        Both = 0x11
    }

    /// <summary>
    /// Print panel selection
    /// </summary>
    public enum PrintPanel : byte
    {
        YMCKO = 0,
        YMCO = 1,
        K = 2,
        KO = 3,
        YMCK = 4,
        YMC = 5
    }

    /// <summary>
    /// Input bin selection
    /// </summary>
    public enum InputBin : byte
    {
        CardFeeder = 0,
        FrontManualSlot = 1,
        BackManualSlot = 2
    }

    /// <summary>
    /// Output bin selection
    /// </summary>
    public enum OutputBin : byte
    {
        OutputHopper = 0,
        FrontManualSlot = 1,
        BackManualSlot = 2,
        RejectBox = 3,
        DoNotEject = 4
    }

    /// <summary>
    /// Feed card mode
    /// </summary>
    public enum FeedCardMode : byte
    {
        NoHookMode = 0x00,
        HookMode = 0x01,
        RetryByHookMode = 0x02,
        HookModeAndRetry = 0x03
    }

    /// <summary>
    /// Common error codes returned by SDK functions
    /// </summary>
    public static class ErrorCode
    {
        // System errors
        public const uint Success = 0;
        public const uint IncorrectFunction = 1;
        public const uint FileNotFound = 2;
        public const uint PathNotFound = 3;
        public const uint AccessDenied = 5;
        public const uint InvalidHandle = 6;
        public const uint NotEnoughMemory = 8;
        public const uint InvalidAccessCode = 12;
        public const uint InvalidData = 13;
        public const uint OutOfMemory = 14;
        public const uint DeviceNotFound = 20;
        public const uint DeviceNotReady = 21;
        public const uint DeviceNotRecognizeCommand = 22;
        public const uint DeviceWriteError = 29;
        public const uint DeviceReadError = 30;
        public const uint DeviceNotFunctioning = 31;
        public const uint NotSupported = 50;
        public const uint PrinterQueueFull = 61;
        public const uint InvalidParameter = 87;
        public const uint OpenFailed = 110;

        /// <summary>Device is busy</summary>
        public const uint DeviceBusy = 170;

        /// <summary>Wait operation timed out</summary>
        public const uint WaitTimeout = 258;

        /// <summary>Device is not connected</summary>
        public const uint DeviceNotConnected = 1167;

        /// <summary>Network connection refused</summary>
        public const uint ConnectionRefused = 10061;

        // Printer-specific errors (0x00010000 range)
        public const uint FirmwareError = 0x00010001;
        public const uint TphThermistorError = 0x00010002;
        public const uint EncoderErrorTake = 0x00010003;
        public const uint EncoderErrorSupply = 0x00010004;
        public const uint AdcError = 0x00010005;
        public const uint EncoderErrorFilm = 0x00010006;

        // Card jam errors (0x00010010 - 0x0001001F)
        public const uint CardJamBase = 0x00010010;

        // Cover/box errors
        public const uint CoverOpen = 0x00010021;
        public const uint RejectboxOpen = 0x00010022;
        public const uint RejectboxFull = 0x00010023;

        // Cam/Motor errors
        public const uint TphCamError = 0x00010031;
        public const uint AdfCamError = 0x00010032;
        public const uint FlipperError = 0x00010033;

        // Ribbon errors (0x00010041 - 0x0001004A)
        public const uint RibbonOut = 0x00010041;
        public const uint RibbonError = 0x00010042;
        public const uint RibbonMissing = 0x00010043;
        public const uint RibbonUnsupport = 0x00010044;
        public const uint RibbonMismatch = 0x00010047;

        // Card feed errors (0x00010051 - 0x0001005F)
        public const uint CardFeedError = 0x00010051;
        public const uint CardOut = 0x0001005F;

        // Film errors (0x00010071 - 0x0001007A)
        public const uint FilmOut = 0x00010071;
        public const uint FilmError = 0x00010072;
        public const uint FilmMissing = 0x00010073;

        // Magnetic stripe errors
        public const uint TrackDataEmpty = 0x00011001;
        public const uint MagEncodingModuleNotAttached = 0x00011005;
        public const uint EncodingMagStripeFail = 0x00011006;
        public const uint FlipperModuleNotAttached = 0x00011007;

        // Security/Lock errors
        public const uint PrinterLocked = 0x00013005;
    }

    /// <summary>
    /// Warning codes from SOY_PR_GetPrinterWarning()
    /// </summary>
    public static class WarningCode
    {
        public const uint RibbonLow = 0x00020001;
        public const uint CardLow3 = 0x00020002;
        public const uint WaitingForCardInsertion = 0x00020003;
        public const uint WaitingForCardRemoval = 0x00020004;
        public const uint CardLow2 = 0x00020005;
        public const uint CardLow1 = 0x00020006;
        public const uint CleaningRecommended = 0x00020009;
    }

    /// <summary>
    /// Font attributes for printing text
    /// </summary>
    [Flags]
    public enum FontAttribute : byte
    {
        Normal = 0x00,
        Bold = 0x01,
        Italic = 0x40,
        Underline = 0x20
    }
}
