// <auto-generated>
// Seaory SDK Native Structures - Ported from SeaoryPrinter.h
// SDK Version: 1.6.4.0
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace luo.dangxiao.printer.Seaory.Native
{
    /// <summary>
    /// Native BITMAP structure for image data.
    /// For S series: 648x1012 pixels, each pixel is 24-bits
    /// For R300: 648x1030 pixels, each pixel is 24-bits
    /// For R600/R600M: 1296x2060 pixels, each pixel is 24-bits
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct NativeBitmap
    {
        /// <summary>Bitmap type</summary>
        public int bmType;
        
        /// <summary>Bitmap width in pixels</summary>
        public int bmWidth;
        
        /// <summary>Bitmap height in pixels</summary>
        public int bmHeight;
        
        /// <summary>Number of bytes per line</summary>
        public int bmWidthBytes;
        
        /// <summary>Number of color planes</summary>
        public short bmPlanes;
        
        /// <summary>Number of bits per pixel</summary>
        public short bmBitsPixel;
        
        /// <summary>Pointer to the bitmap data</summary>
        public IntPtr bmBits;
    }

    /// <summary>
    /// Document properties for print job configuration.
    /// Used with SOY_PR_StartPrinting2A and SOY_PR_ModifyDocumentPropertiesA.
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Ansi)]
    public struct SeaoryDocProp
    {
        /// <summary>1=portrait, 2=landscape</summary>
        public byte byOrientation;
        
        /// <summary>
        /// Ribbon type.
        /// For S series: 0=YMCKO, 1=K, 2=1/2ymcKO, 3=YMCKOK, 4=KO, 5=Gold, 6=Silver, 7=White, 8=1/2ymcKOKO, 9=1/2ymcKO-n, 10=RYMCK, 11=UV, 12=Red, 13=Blue.
        /// For R series: 100=YMCK, 101=YMCKK, 1=K.
        /// </summary>
        public byte byRibbonType;

        /// <summary>0x00=no printing, 0x01=front side, 0x10=back side, 0x11=both sides</summary>
        public byte byPrintSide;
        
        /// <summary>
        /// Print panels for front side when ribbon has YMCKO.
        /// 0=YMCKO, 1=YMCO, 2=K, 3=KO, 4=YMCK, 5=YMC.
        /// For RYMCK ribbon: 0=RYMCK, 1=RYMC, 2=K, 3=RK, 4=RYMCK+R, 5=YMCK+R.
        /// For YMCK ribbon: 0=YMCK, 1=YMC, 2=K.
        /// </summary>
        public byte byPrintPanelFront;
        
        /// <summary>
        /// Print panels for back side when ribbon has YMCKO.
        /// </summary>
        public byte byPrintPanelBack;

        /// <summary>
        /// When byPrintPanelFront is K or KO => 0=Dither, 1=Black/White.
        /// Otherwise => 0=Black text, images and graphics, 1=Black text, 2=All black pixels
        /// </summary>
        public byte byResinKfront;
        
        /// <summary>Same as byResinKfront but for back side</summary>
        public byte byResinKback;
        
        /// <summary>0x00=no rotation, 0x01=rotate front side, 0x10=rotate back side, 0x11=rotate both sides</summary>
        public byte byRotate180;

        /// <summary>0=card feeder, 1=front end manual slot, 2=back end manual slot</summary>
        public byte byInputBin;
        
        /// <summary>0x00=no hook mode, 0x01=hook mode, 0x02=retry by hook mode, 0x03=hook mode+retry by hook mode</summary>
        public byte byFeedCardMode;
        
        /// <summary>0=output hopper, 1=front end manual slot, 2=back end manual slot, 3=reject box, 4=Do not eject card</summary>
        public byte byOutputBin;
        
        /// <summary>0=Output directly, 1=Wait for removal</summary>
        public byte byEjectCardMode;
        
        /// <summary>0=Use card input and output settings by above fields. 1=Use settings saved in device.</summary>
        public byte byCardInOutByDev;

        /// <summary>For S series: 0=300x300dpi, 1=300x600dpi. For R series: ignored.</summary>
        public byte byResolution;
        
        /// <summary>For S20R/S22R only. 0x00=no erase action, 0x01=erase before print, 0x80=erase only</summary>
        public byte byEraseCard;

        /// <summary>0=Use ribbon as byRibbonType setting, 1=auto detect ribbon</summary>
        public byte byAutoDetectRibbon;
        
        /// <summary>0x00=no mirror, 0x01=mirror front side, 0x10=mirror back side, 0x11=mirror both sides</summary>
        public byte byMirror;
        
        /// <summary>0=Normal speed, 1=Print mono ribbon by speed mode. For R series: ignored.</summary>
        public byte byMonoSpeedMode;

        /// <summary>0=Normal color printing by YMC, 1=Print color pixels by gray mode</summary>
        public byte byGrayYMC;
        
        /// <summary>For S series: 0=CR-80, 1=54mm X 114mm(need mono ribbon), 2=A4(need special driver). For R series: ignored.</summary>
        public byte byPaperSize;

        /// <summary>For S series: Left offset of crop position from A4 size. Unit=0.1mm.</summary>
        public ushort wOriginX;
        
        /// <summary>For S series: Top offset of crop position from A4 size. Unit=0.1mm.</summary>
        public ushort wOriginY;

        /// <summary>For Linux only: 1=Save final card data to /tmp when calling SOY_PR_EndPage2()</summary>
        public byte bySaveFinalImage;
        
        public byte by300x1200Mode;

        /// <summary>For R600 series only, do security erase on K panel: 0x00=no, 0x01=front side, 0x10=back side, 0x11=both sides</summary>
        public byte bySecurityErase;
        
        public byte byReserved4;
        public byte byReserved5;
        public byte byReserved6;
        public byte byReserved7;
        public byte byPrintConcaveDigits;

        /// <summary>
        /// Color adjustment array.
        /// [0] Brightness -100 ~ 100
        /// [1] Contrast -100 ~ 100
        /// [2] Sharpness 0 ~ 100
        /// [3] Yellow Balance -100 ~ 100
        /// [4] Magenta Balance -100 ~ 100
        /// [5] Cyan Balance -100 ~ 100
        /// [6] Saturation -100 ~ 100
        /// [7] Gamma (x0.01) 10 ~ 999
        /// </summary>
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
        public short[] ColorAdj;

        // Heating Energy - Front side (-127 ~ 127)
        public sbyte chFrontHeatYMC;
        public sbyte chFrontHeatK;
        public sbyte chFrontHeatO;
        public sbyte chFrontHeatResinK;

        // Heating Energy - Back side
        public sbyte chBackHeatYMC;
        public sbyte chBackHeatK;
        public sbyte chBackHeatO;
        public sbyte chBackHeatResinK;

        // Rewrite card
        public sbyte chFrontHeatWrite;
        public sbyte chFrontHeatErase;

        // R of RYMCK ribbon
        public sbyte chFrontHeatRcv;
        public sbyte chBackHeatRcv;

        // Responsiveness of K of YMCKO
        public sbyte chFrontRespK;
        public sbyte chBackRespK;

        // Responsiveness of resin K
        public sbyte chFrontRespResinK;
        public sbyte chBackRespResinK;

        /// <summary>Reserved bytes</summary>
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 192)]
        public byte[] byReserved;

        /// <summary>
        /// Creates a new SeaoryDocProp with default values
        /// </summary>
        public static SeaoryDocProp Create()
        {
            var prop = new SeaoryDocProp
            {
                ColorAdj = new short[8],
                byReserved = new byte[192]
            };
            return prop;
        }
    }

    /// <summary>
    /// Print card parameters for SOY_PR_PrintOneCardA.
    /// Advanced direct printing with BITMAP data.
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct PrintCardParam
    {
        /// <summary>Size of PRINT_CARD_PARAM structure</summary>
        public uint dwSize;
        
        public uint dwReserve2;
        public uint dwReserve3;
        public uint dwReserve4;

        /// <summary>For S20R/S22R only. Set number of pass for erasing card.</summary>
        public byte byErasePass;
        
        public byte byReserve2;
        public byte byReserve3;
        public byte byReserve4;
        public byte byReserve5;
        public byte byReserve6;
        public byte byReserve7;
        public byte byReserve8;

        /// <summary>Specifies the color data to be printed on front side.</summary>
        public IntPtr lpFrontBGR;
        
        /// <summary>Specifies the K data to be printed on front side. Each pixel with value 0x00 will be transfer to card by K panel.</summary>
        public IntPtr lpFrontK;
        
        /// <summary>Specifies the O data to be printed on front side. Each pixel with value 0x00 will be transfer to card by O panel. If null, O will be printed on full card by default.</summary>
        public IntPtr lpFrontO;

        /// <summary>Specifies the color data to be printed on back side.</summary>
        public IntPtr lpBackBGR;
        
        /// <summary>Specifies the K data to be printed on back side.</summary>
        public IntPtr lpBackK;
        
        /// <summary>Specifies the O data to be printed on back side.</summary>
        public IntPtr lpBackO;

        /// <summary>Specifies the front side erase data for rewrite card, or security erase data R600 series.</summary>
        public IntPtr lpFrontErase;
        
        /// <summary>Specifies the back side security erase data for R600 series.</summary>
        public IntPtr lpBackErase;

        /// <summary>Color adjustment array (same as SEAORY_DOC_PROP)</summary>
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
        public short[] ColorAdj;

        // Heating Energy - Front side (-127 ~ 127)
        public sbyte chFrontHeatYMC;
        public sbyte chFrontHeatK;
        public sbyte chFrontHeatO;
        public sbyte chFrontHeatResinK;

        // Heating Energy - Back side
        public sbyte chBackHeatYMC;
        public sbyte chBackHeatK;
        public sbyte chBackHeatO;
        public sbyte chBackHeatResinK;

        // Rewrite card
        public sbyte chFrontHeatWrite;
        public sbyte chFrontHeatErase;

        // R of RYMCK ribbon
        public sbyte chFrontHeatRcv;
        public sbyte chBackHeatRcv;

        // Responsiveness of K of YMCKO
        public sbyte chFrontRespK;
        public sbyte chBackRespK;

        // Responsiveness of resin K
        public sbyte chFrontRespResinK;
        public sbyte chBackRespResinK;

        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 136)]
        public byte[] byReserveX;

        public byte byPrintConcaveDigits;
        public byte bySpace;
        public byte byReserveC1;
        public byte byReserveC2;
        public ushort wDistance;
        public ushort wReserveC1;
        
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 24)]
        public byte[] szDigitsA;

        /// <summary>
        /// Creates a new PrintCardParam with default values
        /// </summary>
        public static PrintCardParam Create()
        {
            var param = new PrintCardParam
            {
                dwSize = (uint)Marshal.SizeOf<PrintCardParam>(),
                ColorAdj = new short[8],
                byReserveX = new byte[136],
                szDigitsA = new byte[24]
            };
            return param;
        }
    }

    /// <summary>
    /// Indent-printing module hammer parameters
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct IndentHammerParam
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
        public short[] shDigits;
        
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)]
        public short[] shReserved;
    }

    /// <summary>
    /// Indent-printing module disk digit compensation parameters
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct IndentDiskCompParam
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
        public short[] shDigits;
        
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)]
        public short[] shReserved;
    }

    /// <summary>
    /// Print area parameters
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct PrintAreaParam
    {
        // Front side
        public NativeBitmap frontYMCO;
        public NativeBitmap frontK;
        public NativeBitmap frontRewrite;
        public NativeBitmap frontUnused1;

        // Back side
        public NativeBitmap backYMCO;
        public NativeBitmap backK;
        public NativeBitmap backUnused1;
        public NativeBitmap backUnused2;
    }
}
